workers_dev = true
name = "northsky-migration-tool"
compatibility_date = "2025-03-17"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

assets = {}

[vars]
PDS_HOSTNAME = "https://devpds1.northsky.social"
MIGRATOR_BACKEND = "http://localhost:9090"
PLC_HOSTNAME = "https://devplc.northsky.social"

[env.staging.vars]
PDS_HOSTNAME = "https://devpds2.northsky.social"
MIGRATOR_BACKEND = "https://migrator.northsky.social"
PLC_HOSTNAME = "https://devplc.northsky.social"

[env.production.vars]
PDS_HOSTNAME = "https://northsky.social"
MIGRATOR_BACKEND = "https://migrator.northsky.social"
