workers_dev = true
name = "northsky-migration-tool"
compatibility_date = "2025-03-17"
compatibility_flags = [ "nodejs_compat" ]
main = "./workers/app.ts"

assets = {}

[vars]
PDS_HOSTNAME = "https://pds-dest.aendra.dev"
MIGRATOR_BACKEND = "http://localhost:9090"