workers_dev = true
name = "northsky-migration-tool"
compatibility_date = "2025-02-23"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"