// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/failed": {
    params: {};
  };
  "/success": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/failed" | "/success";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/failed.tsx": {
    id: "routes/failed";
    page: "/failed";
  };
  "routes/success.tsx": {
    id: "routes/success";
    page: "/success";
  };
};