apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-fe-${PR_NUMBER}
  namespace: staging
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: pr-${PR_NUMBER}-ttl
    uid: ${JOB_UID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration-fe-${PR_NUMBER}
  template:
    metadata:
      labels:
        app: migration-fe-${PR_NUMBER}
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: migration-fe-${PR_NUMBER}
        image: ghcr.io/northskysocial/migration-fe:pr-${PR_NUMBER}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: PDS_HOSTNAME
            value: "https://northsky.social"
          - name: MIGRATOR_BACKEND
            value: "https://migrator.northsky.social"
          - name: HOSTNAME
            value: "pr-${PR_NUMBER}.pr.migrate.staging.northsky.social"
          - name: PLC_HOSTNAME
            value: "https://plc.directory"
          - name: REDIS_URL
            value: "redis://valkey.migration-fe.svc.cluster.local:6379"
        resources:
          requests:
            memory: "56Mi"
            cpu: "25m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 20
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: migration-fe-${PR_NUMBER}
  namespace: staging
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: pr-${PR_NUMBER}-ttl
    uid: ${JOB_UID}
spec:
  selector:
    app: migration-fe-${PR_NUMBER}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: migration-fe-${PR_NUMBER}-ingress
  namespace: staging
  ownerReferences:
  - apiVersion: batch/v1
    kind: Job
    name: pr-${PR_NUMBER}-ttl
    uid: ${JOB_UID}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "2048m"

    nginx.ingress.kubernetes.io/session-cookie-name: "northskypdsaffinity"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"

    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pr-${PR_NUMBER}.pr.migrate.staging.northsky.social
    secretName: pr-${PR_NUMBER}-tls-secret
  rules:
  - host: pr-${PR_NUMBER}.pr.migrate.staging.northsky.social
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: migration-fe-${PR_NUMBER}
            port:
              number: 80
